### ISSUE TITLE
eetcd_kv:with_prefix/1 is broken

### ISSUE THREAD

**Issue by f355** [zhongwencool/eetcd#14]
`eetcd_kv:with_prefix/1` is supposed to return all the keys that start with a certain prefix, instead it returns all the keys that are greater than or equal to that prefix.

I believe the bug is here: https://github.com/zhongwencool/eetcd/blob/master/src/eetcd_kv.erl#L50. The correct behavior is described in the proto file comments here: https://github.com/etcd-io/etcd/blob/master/etcdserver/etcdserverpb/rpc.proto#L410.

**Comment by zhongwencool** [comment]
Good catch!
I can fix this in v0.3.0, and add more tests.

**Comment by michaelklishin** [comment]
A minimal test that reproduces:

``` erlang
prefix(Config) ->
    [{Kv1, Vv1}, {Kv2, Vv2}, {Kv3, Vv3}, {Kv4, Vv4}, {Kv5, Vv5} | _] = KVs = get_kvs(Config),
    %% seed all keys
    lists:foreach(fun({Key, Val}) ->
                    Ctx = eetcd_kv:new(?NAME(Config)),
                    Ctx1 = eetcd_kv:with_value(eetcd_kv:with_key(Ctx, Key), Val),
                    eetcd_kv:put(Ctx1)
                  end, KVs),
    %% find keys prefixed with an "a"
    Ctx1 = eetcd_kv:new(?NAME(Config)),
    {ok, #{header := #{}, more := false, count := 4, kvs := Kvs}}
        = eetcd_kv:get(eetcd_kv:with_range_end(eetcd_kv:with_key(Ctx1, Kv1), Kv5)),

    %% we expect results a1 through a4 but not v2 or z3
    ?assert(includes_key(Kv1, KVs)),
    ?assert(includes_key(Kv2, KVs)),
    ?assert(includes_key(Kv3, KVs)),
    ?assert(includes_key(Kv4, KVs)),
    ?assertNot(includes_key(?KEY("r8"), KVs)),
    ?assertNot(includes_key(?KEY("v2"), KVs)),
    ?assertNot(includes_key(?KEY("z3"), KVs)),

    ct:pal("KVs: ~p", [KVs]),

    ok.

includes_key(KeyTarget, KVs) ->
    lists:any(fun ({Key, _Val}) -> Key =:= KeyTarget end, KVs).
```

I'm looking into it.

**Comment by zhongwencool** [comment]
Yes,  but `eetcd:with_prefix` is not correct.
https://github.com/zhongwencool/eetcd/blob/master/src/eetcd_kv.erl#L48-L50

the correct way to do this by following the official doc.
https://github.com/etcd-io/etcd/blob/aa016eebf8a18ca3ced2fca9137c9963d8a648f2/clientv3/op.go#L383-L391
But I don't understand the`getPrefix` function yet, and don't know how to generate a `0xff`.
https://play.studygolang.com/p/KOmE5qLSop1
```golang
package main

import (
	"fmt"
)

func main() {
	t := "AAAA中国BBB中"
	// t := "ABC12"
	fmt.Println([]byte(t))
	fmt.Println(getPrefix([]byte(t)))
}

func getPrefix(key []byte) []byte {
	end := make([]byte, len(key))
	copy(end, key)
	for i := len(end) - 1; i >= 0; i-- {
		if end[i] < 0xff {
			end[i] = end[i] + 1
			end = end[:i+1]
			return end
		}
	}
	// next prefix does not exist (e.g., 0xffff);
	// default to WithFromKey policy
	return []byte{0}
}
```
The output is
```
[65 65 65 65 228 184 173 229 155 189 66 66 66 228 184 173]
[65 65 65 65 228 184 173 229 155 189 66 66 66 228 184 174]
```

**Comment by zhongwencool** [comment]
I think I figure it out: 
this keypoint is 
`"ABCxxxx"` is between `"ABC"` and `"ABD"`
```erlang
%% @doc Enables `get', `delete' requests to operate
%% on the keys with matching prefix. For example, `get("foo", with_prefix())'
%% can return 'foo1', 'foo2', and so on.
-spec with_prefix(context()) -> context().
with_prefix(Context) ->
    #{key => Key} = Context,
    case Key == <<>> or Key == "" of
        true ->
            Context#{key => "", range_end => ""};
        false ->
            KeyList = case is_binary(Key) of true -> binary_to_list(Key); false -> Key end,
            {Prefix, Last} = lists:split(length(Key)-1, KeyList),
            with_range_end(Context, Prefix ++ [ C+1||C<- Last])
    end.
```

**Comment by michaelklishin** [comment]
@zhongwencool I'm arriving at a different implementation. Note that both `Key` and `KeyList` in your case are of the same length (we are operating on bytes, not code points), so the suffix part is going to be a single character. The output of your small Go program differs in just one position — the last one.

I'll submit a PR and we can discuss it there.

**Comment by michaelklishin** [comment]
I think we can produce a new release now that this has been addressed.

**Comment by zhongwencool** [comment]
`v0.3.0` is ready.
