### ISSUE TITLE
Usage question

### ISSUE THREAD

**Issue by benbro** [zhongwencool/eetcd#15]
I've read the README but it's still not clear to me. Can you please explain how to do the following?

1. Create 'room-100' key with 'server-5' value and 60 seconds TTL, only if the key doesn't already exists.
2. Detect error if the 'room-100' key already exists with a different value.
3. Every 30 seconds reset the 'room-100' key only if it still has the same value 'server-5'.
4. Get a list of all keys with 'room-' prefix and their values.

**Comment by zhongwencool** [comment]
https://github.com/etcd-io/etcd/blob/e6980b1f9f/Documentation/rfc/v3api.md
https://github.com/etcd-io/etcd/blob/master/etcdserver/etcdserverpb/rpc.proto
https://github.com/etcd-io/etcd/blob/master/mvcc/mvccpb/kv.proto

This will help you.
