### ISSUE TITLE
Locking service client is missing

### ISSUE THREAD

**Issue by michaelklishin** [zhongwencool/eetcd#16]
I could not find any [lock RPC](https://godoc.org/github.com/etcd-io/etcd/etcdserver/api/v3lock/v3lockpb) support in the API. I think the API can look a bit like this:

``` erlang
-spec eetcd_lock:lock(Ctx :: map(), Name :: binary(), TTL :: pos_integer()) -> lock_response().

-spec eetcd_lock:unlock(Ctx :: map(), Name :: binary()) -> unlock_response().

-spec eetcd_lock:try_acquire(Ctx :: map(), Name :: binary(), TTL :: pos_integer(), Timeout :: pos_integer()) -> lock_response().
```

Which largely represents the [Protobuf 3 spec](https://github.com/etcd-io/etcd/blob/master/Documentation/dev-guide/api_concurrency_reference_v3.md#service-lock-etcdserverapiv3lockv3lockpbv3lockproto) except that instead of asking for a lease ID we'd acquire one
using the provided TTL.

**Comment by zhongwencool** [comment]
THANKS for your help!!

**Comment by michaelklishin** [comment]
Looking at Go and Python clients, the Go one relies on the `context` library for operation cancellation but otherwise looks very similar to the idea above. Python clients are built around objects and usually offer APIs that are much broader than this.

So a couple of questions are:

 * Do we want any blocking/waiting functions?
 * If so, do we need another parameter for specifying a timeout?

@zhongwencool let me know what you think.

**Comment by zhongwencool** [comment]
Why do we need to cancel a request halfway?
if you want to specify a timeout :
```
Ctx0 = eetcd_kv:new(),
Ctx1 = eetcd_kv:with_timeout(Ctx0, 2000),
Ctx2 = eetcd_kv:with_key(Ctx1, Key),
eetcd_kv:put(Ctx2).
```
Is this enough?

**Comment by michaelklishin** [comment]
@zhongwencool I have added a `lock.proto` and can see that [rebar3_eetcd_plugin](https://github.com/zhongwencool/rebar3_eetcd_plugin/blob/master/src/rebar3_eetcd_prv_compile.erl) generates a `lock_pb.erl` file but not `eetcd_lock_gen.erl`.

I also found it confusing that some files only include message definitions (e.g. `kv.proto`) and `router.proto` seems to be include most if not all service definitions. Is there a reason for this and should I follow this model?

**Comment by michaelklishin** [comment]
Further inspection of existing clients and etcd code suggests that several of them provide a client- and transaction-driven "try to acquire" operation, e.g. [in Python](https://github.com/kragniz/python-etcd3/blob/master/etcd3/locks.py#L49). I'm adding this to the proposed API.

**Comment by zhongwencool** [comment]
This acquires API implement by `Txn`, not lock API.
https://github.com/etcd-io/etcd/blob/master/clientv3/concurrency/mutex.go#L120
so the lock API and the mutex(acquire) API should apart?

**Comment by michaelklishin** [comment]
I think they can be different functions in the same module, that's what I'm working on. I updated the example.

**Comment by michaelklishin** [comment]
Apparently the etcd v3 locking API uses a non-standard path, `/v3lockpb.Lock/{method}` vs `/etcdserverpb.{service}/{method}` used by other services such as `KV` and `Watch`.  I am working on a PR for `rebar3 etcd gen` to special case it 😢

**Comment by zhongwencool** [comment]
The `etcdserverpb` is hardcode in https://github.com/zhongwencool/rebar3_eetcd_plugin/blob/eac27e35c014b127efc96deb0eb371464298d985/priv/eetcd_sample_client.erl#L21
Maybe you can add new sample file.

**Comment by zhongwencool** [comment]
By the way, I want to implement the election leader feature. But I'm confused by this code:
https://github.com/etcd-io/etcd/blob/master/clientv3/concurrency/election.go
https://github.com/etcd-io/etcd/blob/master/etcdserver/api/v3election/v3electionpb/v3election.proto

I want to port concurrency/election.go firstly, But then find v3election.proto, I don't know which one to follow?
Do you have any idea?

**Comment by michaelklishin** [comment]
The former (`election.go`) is a Go client library. It relies on the general client and implements a pattern. The protocol part defines services that are also exposed via the gRPC/HTTP2-JSON gateway, so it targets a different set of clients if you will.

In this library's case it makes sense to reimplement `election.go` in a way that makes sense for Erlang.

**Comment by michaelklishin** [comment]
As a mostly unrelated note, having implemented lock service support in #26, I think implementing a client [for leader election services](https://github.com/etcd-io/etcd/blob/master/Documentation/dev-guide/api_concurrency_reference_v3.md) can be done in the same way, and would still be quite useful in Erlang without any additional functions in this client.

I'd be happy to take a look but RabbitMQ needs locking service support first.

**Comment by michaelklishin** [comment]
I can use a Git ref dependency but I think it might be a good moment to produce a new release before the work on leader election services begins.

**Comment by zhongwencool** [comment]
`v0.3.1` is ready.
