### ISSUE TITLE
Awesome

### ISSUE THREAD

**Issue by turtleDeng** [zhongwencool/eetcd#36]
Thank you very much for your contribution, we will integrate it into the https://github.com/emqx/ekka etcd cluster.

If you have better suggestions, please contact me deng@emqx.io, EMQ Team

**Comment by zhongwencool** [comment]
Looks great! 
If you’re not in a hurry, I can help send PR to ekka before Saturday. :0

**Comment by turtleDeng** [comment]
Thanks, our colleagues have created PR https://github.com/emqx/ekka/pull/88.
Very happy to meet you!
Are you interested in joining our EMQ? Build a strong Erlang community together！

**Comment by zhongwencool** [comment]
Thanks for inviting me, but I don’t plan to change my job recently, and Hangzhou is too far away for me.
By the way, I learn interesting things when digging `emqx` project.  **NB!**

**Comment by turtleDeng** [comment]
EMQ is an open team.
Looking forward to discussing many Erlang performance optimization issues with you.
Can you add your WeChat?
This is my WeChat 18665330643.
